baseURL: https://daria-website.netlify.app/
languageCode: en-us
title: My Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      WELCOME TO MY WEBSITE! JOIN ME ON MY JOURNEY AT
      LONDON BUSINESS SCHOOL.
    title: Hi, my name is Daria. 
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: daria@email.com
        title: Email
    enable: yes
    phone:
      - phone: (020) 7000-7000 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/daria-gamaley
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/daria-gamaley/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs
      - name: Portfolio
        url: blogs/my-background
      # - name: Elements ## this helps customize 
      #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: From building to banking
        title: Professional Background
        url: blogs/professional
      - image: pic02.jpg
        subtitle: A sneak-peak of data analysis
        title: My Portfolio
        url: blogs/my-portfolio
      - image: pic03.jpg
        subtitle: A glimpse in my kaleidoscope of thoughs
        title: My Hobbies
        url: blogs/hobbies
      - image: pic04.jpg
        subtitle: Twenty-three turns around the sun
        title: My Background
        url: blogs/my-background
      # - image: pic05.jpg
      #   subtitle: Ipsum Dolor Sit Amet
      #   title: Consequat
      #   url: blogs/my-background
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Etiam
      #   url: blogs/my-background
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
