baseURL: https://daria-website.netlify.app/
languageCode: en-us
title: My Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      WELCOME TO MY WEBSITE! JOIN ME ON MY JOURNEY AT
      LONDON BUSINESS SCHOOL.
    title: Hi, my name is Daria.
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    # buttonClear: Clear
    # buttonSend: Send message
    email:
      - email: dgamaley.mfa2022@london.edu
        title: Email
    # enable: yes
    phone:
      - phone: (020) 7000-7000 
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Daria Gamaley
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/daria-gamaley
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/daria-gamaley/
  image: london-business-school.jpeg
  name: Daria
  navigation:
    button1:
      - name: Get Started
        url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs
      - name: Portfolio
        url: blogs/my-background
      # - name: Elements ## this helps customize 
      #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: the-shard.jpeg
        subtitle: From building to banking
        title: Professional Background
        url: blogs/professional
      - image: data.jfif
        subtitle: A sneak-peak of data analytics
        title: Course Portfolio
        url: blogs/my-portfolio
      - image: Zermatt.png
        subtitle: A glimpse in my kaleidoscope of thoughs
        title: Hobbies & Interests
        url: blogs/hobbies
      - image: london.jfif
        subtitle: Twenty-three turns around the sun
        title: Academic Background
        url: blogs/my-background
      # - image: pic05.jpg
      #   subtitle: Ipsum Dolor Sit Amet
      #   title: Consequat
      #   url: blogs/my-background
      # - image: pic06.jpg
      #   subtitle: Feugiat Amet Tempus
      #   title: Etiam
      #   url: blogs/my-background
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "The 'Six Degrees of Separation' theory states that all people on this globe are six or fewer social connections away from each other. Let's find out how we're connected!"
    title: Let's Connect!
    url: blogs
